# Generated by Django 5.1.7 on 2025-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_trainning_app', '0004_remove_user_peso_maximo_rm_userexerciserm'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdata',
            name='rm_sesion',
            field=models.FloatField(default=0.0, verbose_name='Estimated 1RM (Session)'),
        ),
    ]
