# Generated by Django 5.1.7 on 2025-03-13 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_trainning_app', '0005_workoutdata_rm_sesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexerciserm',
            options={
                'ordering': ['-fecha_registro'],
                'verbose_name': 'User Exercise 1RM',
                'verbose_name_plural': 'User Exercise 1RMs'},
        ),
        migrations.AlterUniqueTogether(
            name='userexerciserm',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userexerciserm',
            name='fecha_registro',
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name='Date Recorded'),
        ),
    ]
